In [2]:
import pandas as pd

data = pd.read_csv("DisasterDeclarationsSummaries.csv")

data.head()

,femaDeclarationString,disasterNumber,state,declarationType,declarationDate,fyDeclared,incidentType,declarationTitle,ihProgramDeclared,iaProgramDeclared,...,placeCode,designatedArea,declarationRequestNumber,lastIAFilingDate,incidentId,region,designatedIncidentTypes,lastRefresh,hash,id
0,FM-5529-OR,5529,OR,FM,2024-08-09T00:00:00.000Z,2024,Fire,LEE FALLS FIRE,0,0,...,99067,Washington (County),24122,NaN,2024081001,10,R,2024-08-27T18:22:14.800Z,ae87cf3c6ed795015b714af7166c7c295b2b67c7,09e3f81a-5e16-4b72-b317-1c64e0cfa59c
1,FM-5528-OR,5528,OR,FM,2024-08-06T00:00:00.000Z,2024,Fire,ELK LANE FIRE,0,0,...,99031,Jefferson (County),24116,NaN,2024080701,10,R,2024-08-27T18:22:14.800Z,432cf0995c47e3895cea696ede5621b810460501,59983f89-30bf-4888-b21b-62e8d57d9aac
2,FM-5527-OR,5527,OR,FM,2024-08-02T00:00:00.000Z,2024,Fire,MILE MARKER 132 FIRE,0,0,...,99017,Deschutes (County),24111,NaN,2024080301,10,R,2024-08-27T18:22:14.800Z,2f21d90cb6bc64b0d4121aa3f18d852bbb4b11fa,8d13ecf0-bc2f-496b-8c9f-b2e73da832a0
3,DR-4312-CA,4312,CA,DR,2017-05-02T00:00:00.000Z,2017,Severe Storm,FLOODING,0,0,...,60347,Resighini Rancheria (Indian Reservation),17035,NaN,2017041001,9,NaN,2025-03-26T20:21:32.579Z,432a3a64bdbb291ae26cf5a27a33deeabb380481,98a7c5bb-2346-45aa-a1ca-0399440d4f0b
4,DR-4251-AL,4251,AL,DR,2016-01-21T00:00:00.000Z,2016,Severe Storm,"SEVERE STORMS, TORNADOES, STRAIGHT-LINE WINDS,...",0,0,...,99001,Autauga (County),16003,NaN,2015122301,4,NaN,2025-03-27T12:21:46.559Z,dcd4ce6b37ee49875b3f1e32e9a8a16cd6a803d3,5229bbae-eee6-42b8-b277-edbafa8d6cb2

In [3]:
data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69634 entries, 0 to 69633
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   femaDeclarationString     69634 non-null  object
 1   disasterNumber            69634 non-null  int64
 2   state                     69634 non-null  object
 3   declarationType           69634 non-null  object
 4   declarationDate           69634 non-null  object
 5   fyDeclared                69634 non-null  int64
 6   incidentType              69634 non-null  object
 7   declarationTitle          69634 non-null  object
 8   ihProgramDeclared         69634 non-null  int64
 9   iaProgramDeclared         69634 non-null  int64
 10  paProgramDeclared         69634 non-null  int64
 11  hmProgramDeclared         69634 non-null  int64
 12  incidentBeginDate         69634 non-null  object
 13  incidentEndDate           68801 non-null  object
 14  disasterCloseoutDate      53261 non-null  object
 15  tribalRequest             69634 non-null  int64
 16  fipsStateCode             69634 non-null  int64
 17  fipsCountyCode            69634 non-null  int64
 18  placeCode                 69634 non-null  int64
 19  designatedArea            69634 non-null  object
 20  declarationRequestNumber  69634 non-null  int64
 21  lastIAFilingDate          19433 non-null  object
 22  incidentId                69634 non-null  int64
 23  region                    69634 non-null  int64
 24  designatedIncidentTypes   21822 non-null  object
 25  lastRefresh               69634 non-null  object
 26  hash                      69634 non-null  object
 27  id                        69634 non-null  object
dtypes: int64(13), object(15)
memory usage: 14.9+ MB

,disasterNumber,fyDeclared,ihProgramDeclared,iaProgramDeclared,paProgramDeclared,hmProgramDeclared,tribalRequest,fipsStateCode,fipsCountyCode,placeCode,declarationRequestNumber,incidentId,region
count,69634.000000,69634.000000,69634.000000,69634.000000,69634.000000,69634.000000,69634.000000,69634.000000,69634.000000,69634.000000,69634.000000,6.963400e+04,69634.000000
mean,2714.136370,2005.946391,0.167045,0.246819,0.935621,0.431126,0.002398,31.394836,97.684522,96472.979450,34189.613278,1.609792e+09,5.178835
std,1437.694226,15.202781,0.373019,0.431164,0.245429,0.495237,0.048914,16.627488,102.131093,13660.356858,33657.667364,1.244842e+09,2.112520
min,1.000000,1953.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,3.000000,5.300300e+04,1.000000
25%,1392.250000,1998.000000,0.000000,0.000000,1.000000,0.000000,0.000000,19.000000,31.000000,99029.000000,9081.000000,9.806600e+04,4.000000
50%,3190.000000,2008.000000,0.000000,0.000000,1.000000,0.000000,0.000000,29.000000,75.000000,99073.000000,20062.000000,2.008100e+09,5.000000
75%,4015.000000,2020.000000,0.000000,0.000000,1.000000,1.000000,0.000000,46.000000,127.000000,99125.000000,72034.000000,2.020031e+09,7.000000
max,5621.000000,2026.000000,1.000000,1.000000,1.000000,1.000000,1.000000,78.000000,840.000000,99507.000000,99159.000000,9.062400e+09,10.000000

In [4]:
data.isnull().sum()

femaDeclarationString           0
disasterNumber                  0
state                           0
declarationType                 0
declarationDate                 0
fyDeclared                      0
incidentType                    0
declarationTitle                0
ihProgramDeclared               0
iaProgramDeclared               0
paProgramDeclared               0
hmProgramDeclared               0
incidentBeginDate               0
incidentEndDate               833
disasterCloseoutDate        16373
tribalRequest                   0
fipsStateCode                   0
fipsCountyCode                  0
placeCode                       0
designatedArea                  0
declarationRequestNumber        0
lastIAFilingDate            50201
incidentId                      0
region                          0
designatedIncidentTypes     47812
lastRefresh                     0
hash                            0
id                              0
dtype: int64

In [13]:
data = data[['state', 'incidentType', 'declarationDate']]
data['declarationDate'] = pd.to_datetime(data['declarationDate'], errors='coerce')
data['year'] = data['declarationDate'].dt.year
data['month'] = data['declarationDate'].dt.month

In [ ]:
data = data.dropna()

In [14]:
data = data.drop_duplicates()

In [12]:
data.to_csv("usnd_cleaned.csv", index=False)

In [15]:
data.head()

  state  incidentType           declarationDate  year  month
0    OR          Fire 2024-08-09 00:00:00+00:00  2024      8
1    OR          Fire 2024-08-06 00:00:00+00:00  2024      8
2    OR          Fire 2024-08-02 00:00:00+00:00  2024      8
3    CA  Severe Storm 2017-05-02 00:00:00+00:00  2017      5
4    AL  Severe Storm 2016-01-21 00:00:00+00:00  2016      1

In [17]:
import os
os.listdir()

['.ipynb_checkpoints',
 'DisasterDeclarationsSummaries.csv',
 'disaster_analysis',
 'milestone2_temporal_analysis.ipynb',
 'usnd_cleaned.csv',
 'usnd_cleaned.ipynb']